/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker\wrangler.jsonc --include-runtime=false worker\worker-configuration.d.ts` (hash: 96336b2a46b565fffaccb46b61b92063)
interface __BaseEnv_Env {
	MARKET_CACHE: KVNamespace;
	/** 選用：以 `wrangler secret put HEALTH_KEY` 設定後，/health?deep=1 需帶 key 參數 */
	HEALTH_KEY?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
